#!/bin/bash

ffamily=$1
shift

case $ffamily in
    "MinionPro" | "MyriadPro" | "CronosPro")
	echo "Chosen font family is $ffamily"
	echo "$ffamily" > fontname
	;;
    *)
	echo "Entered font not supported"
	exit 1
	;;
esac

case $ffamily in
    "CronosPro")
	math=false
	;;
    *)
	math=true
	;;
esac

ADDPACK=""
case "$*" in
    *--pack*) echo Using explicitly given glyph list;;
    *)  fontver=$(otfinfo -v otf/${ffamily}-Regular.otf | \
	          sed -e 's/[[:alpha:]]* \([[:digit:]]*\.[[:digit:]]*\).*/\1/')
	echo Found font version ${fontver}
	if [ -e "scripts/${ffamily}-glyph-list-${fontver}" ]; then
	    echo Using glyph list "scripts/${ffamily}-glyph-list-${fontver}"
	    ADDPACK="--pack=scripts/${ffamily}-glyph-list-${fontver}"
	else
	    echo "No matching glyph list found"
	    echo "Please run \"scripts/generate-glyph-list.sh > scripts/${ffamily}-glyph-list-${fontver}\" after this script and use the resulting file with a clean script folder"
	fi
	;;
esac


cp enc/$ffamily/* enc/
cp fontinst/$ffamily/* fontinst/
cp kerning/$ffamily/* kerning/

case "$*" in
  *--verbose*) verbose=true;;
  *)           verbose=false;;
esac

mkdir -p pfb tfm vf dvips

echo "Creating PostScript fonts ..."

for font in otf/$ffamily*.otf
do
  base=$(basename "$font" .otf)
  cfftot1    "$font"     "$base.pfb"
  t1dotlessj "$base.pfb" "${base}LCDFJ.pfb"
done

echo "Creating TeX metrics ..."

maketfm() {
  local family="$1"
  shift

  # We pass the error code of maketfm via a stamp file.
  touch maketfm.error

  ( scripts/maketfm "$family" "$@" >"dvips/$family.map.tmp" && rm maketfm.error ) 2>&1 |
  ( ( ! $verbose && perl scripts/filtererr ) || cat )

  sed -e "s/\.otf$/.pfb/" <"dvips/$family.map.tmp" | sort -u >"dvips/$family.map"
  rm "dvips/$family.map.tmp"
}

maketfm $ffamily "$@" $ADDPACK

mv *.pfb pfb

if [ -e maketfm.error ]
then
  rm maketfm.error
  echo "maketfm failed, exiting ..."
  exit 1
fi

if $math; then
    (cd fontinst; ../scripts/makeint $ffamily; ../scripts/makeoml $ffamily)
fi

(cd tex; latex $ffamily.ins; latex otfontdef.ins)

